### ISSUE TITLE
Need help with sample projects / documentation?

### ISSUE THREAD

**Issue by RyanONeill1970** [Virtuoze/Puresharp#1]
Hi Tony,

I'd like to use your project to weave logging into every class in an assembly. I can't see an easy way to get started though. If you have a small sample I'm happy to write a blog post on how to use it in .Net Core and for the wiki here.

Regards

Ryan

**Comment by Virtuoze** [comment]
Hi, thank you for your interest.
Sorry for being inactive for month... I was too busy to work on my projects, I'm now ready to consolidate all this work with exclusive features, tests and documentations (step by step / get started).

**Comment by RyanONeill1970** [comment]
Understood, I can try and make time if you find some small tasks that need work.

**Comment by Virtuoze** [comment]
I keep this issue open until basic documentation will be provided.
