### ISSUE TITLE
Difference between Puresharp and Puresharper

### ISSUE THREAD

**Issue by artemsv** [Virtuoze/Puresharp#2]
Hi Tony,

Thank you for you fantastic project! I would like to use it in our projects, I just wanted to know what is the difference between that two projects - as I see they do pretty the same thing but one with Reflection another with Confluence and both should be started after my project is built to handle it.

**Comment by Virtuoze** [comment]
Sorry for answer just now but Puresharp replace Puresharper, and confluence replace Puresharp. I changed a point of view to prepare public release without remove legacy to fast.

Now Puresharp is the IL rewriter and Puresharp.XXX (Confluence for example) are libraries.
