### ISSUE TITLE
Support .NET Core SDK Projects

### ISSUE THREAD

**Issue by Trojaner** [Virtuoze/Puresharp#9]
Currently the project does not support .NET Core projects (even if targeting net472).

The reason for this is the wrong location to the IPuresharp.exe. With .NET Core SDK templates, the "packages" folder inside solution root is not used anymore.

For me it is located at `C:\Users\USERNAME\.nuget\packages\ipuresharp\4.2.1` instead.

**Comment by Puresharper** [comment]
Hi, not sure even if I fix the nuget path to run IPuresharp.exe, dotnetcore will work fine. I have to try limitations of mono.cecil to support dotnet core.

**Comment by Trojaner** [comment]
Problem is not that it does not support .NET Core runtime, problem is that it does not support .NET Core Project SDK templates, which still can target full .NET Framework like v4.7.2

**Comment by Puresharper** [comment]
Ok, I fixed it in IPuresharp.4.2.5 by prior legacy path resolution ($(Solution)\packages\IPuresharp.x.x.x) but fallback to %USERPROFILE%\.nuget\packages\IPuresharp\x.x.x when not found.
